import csv
import random
import statistics

import math
import numpy as np
import networkx as nx

from src import (
    estimate_cascade_by_community,
    estimate_cascade_influence,
    utility_gap,
)
from src import opt_kempe_greedy, opt_welfare_greedy, opt_c_fim

# Parameters
k = 3  # seed set size
p = 0.01  # propagation probability
num_sims = 1000
num_runs = 3  # Number of runs to average


def create_sbm_graph(seed: int = 42):
    """
    Create a Stochastic Block Model (SBM) graph with three communities on 5,000 nodes.

    Parameters
    ----------
    seed : int, optional
        Random seed for reproducibility.

    Returns
    -------
    G : networkx.Graph
        An undirected graph generated by the SBM. Each node has a
        'community' attribute in {0, 1, 2}.
    """
    sizes = [2000, 1700, 1300]
    assert sum(sizes) == 5000

    P = [
        [0.018, 0.0025, 0.0015],
        [0.0025, 0.015, 0.0020],
        [0.0015, 0.0020, 0.012],
    ]

    rng = np.random.default_rng(seed)

    G = nx.stochastic_block_model(
        sizes,
        P,
        seed=rng,
        directed=True,
    )

    start = 0
    for cid, sz in enumerate(sizes):
        for node in range(start, start + sz):
            G.nodes[node]["community"] = cid
        start += sz

    base_cost = 1.0
    degree_weight = 0.5
    costs = {}
    for node, deg in G.degree():
        cost = base_cost + degree_weight * math.log1p(deg)
        costs[node] = float(cost)
        G.nodes[node]['node_cost'] = float(cost)

    return G, costs


def compute_greedy_baseline(graph, k_fixed):
    """Compute greedy baseline once and return all metrics"""
    greedy_seeds = opt_kempe_greedy(
        graph=graph,
        k=k_fixed,
        probability=p,
        num_simulations=num_sims,
    )
    greedy_total_influence = estimate_cascade_influence(
        graph=graph,
        seeds=greedy_seeds,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    greedy_by_comm = estimate_cascade_by_community(
        graph=graph,
        seeds=greedy_seeds,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    greedy_ugap = utility_gap(greedy_by_comm)

    return {
        'seeds': greedy_seeds,
        'total_influence': greedy_total_influence,
        'ugap': greedy_ugap,
        'by_comm': greedy_by_comm
    }


def run_test1_single_alpha(graph, costs, k_fixed, alpha, greedy_baseline):
    """Run a single Test 1 experiment for one alpha value, using precomputed greedy baseline"""

    # Welfare Greedy at this alpha
    welfare_seeds = opt_welfare_greedy(
        graph=graph,
        k=k_fixed,
        probability=p,
        num_sims=num_sims,
        alpha=alpha,
    )
    welfare_total_influence = estimate_cascade_influence(
        graph=graph,
        seeds=welfare_seeds,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    welfare_by_comm = estimate_cascade_by_community(
        graph=graph,
        seeds=welfare_seeds,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    welfare_ugap = utility_gap(welfare_by_comm)

    # C-FIM constrained to select at most k seeds
    cfim_seeds = opt_c_fim(
        graph=graph,
        budget=k_fixed,  # interpret as seed-count cap
        costs=costs,
        alpha=alpha,
        probability=p,
        num_sims=1000,
    )
    cfim_total_influence = estimate_cascade_influence(
        graph=graph,
        seeds=cfim_seeds,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    cfim_by_comm = estimate_cascade_by_community(
        graph=graph,
        seeds=cfim_seeds,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    cfim_ugap = utility_gap(cfim_by_comm)

    pof_welfare = 1 - (welfare_total_influence / greedy_baseline['total_influence']) if greedy_baseline[
                                                                                            'total_influence'] > 0 else 0
    pof_cfim = 1 - (cfim_total_influence / greedy_baseline['total_influence']) if greedy_baseline[
                                                                                      'total_influence'] > 0 else 0

    return {
        'greedy_total_influence': greedy_baseline['total_influence'],
        'greedy_ugap': greedy_baseline['ugap'],
        'welfare_total_influence': welfare_total_influence,
        'welfare_ugap': welfare_ugap,
        'cfim_total_influence': cfim_total_influence,
        'cfim_ugap': cfim_ugap,
        'pof_welfare': pof_welfare,
        'pof_cfim': pof_cfim
    }


def run_test2_single(graph, costs, k_budget, alpha_fixed):
    """Run a single Test 2 experiment"""

    # Greedy at this k (baseline for PoF)
    greedy_seeds_k = opt_kempe_greedy(
        graph=graph,
        k=k_budget,
        probability=p,
        num_simulations=num_sims,
    )
    greedy_total_influence_k = estimate_cascade_influence(
        graph=graph,
        seeds=greedy_seeds_k,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    greedy_by_comm_k = estimate_cascade_by_community(
        graph=graph,
        seeds=greedy_seeds_k,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    greedy_ugap_k = utility_gap(greedy_by_comm_k)

    # Welfare Greedy at this k and alpha
    welfare_seeds_k = opt_welfare_greedy(
        graph=graph,
        k=k_budget,
        probability=p,
        num_sims=num_sims,
        alpha=alpha_fixed,
    )
    welfare_total_influence_k = estimate_cascade_influence(
        graph=graph,
        seeds=welfare_seeds_k,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    welfare_by_comm_k = estimate_cascade_by_community(
        graph=graph,
        seeds=welfare_seeds_k,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    welfare_ugap_k = utility_gap(welfare_by_comm_k)

    # C-FIM at this k
    cfim_seeds = opt_c_fim(
        graph=graph,
        budget=k_budget,  # interpreted as seed count budget
        costs=costs,
        alpha=alpha_fixed,
        probability=p,
        num_sims=1000,
    )
    cfim_total_influence = estimate_cascade_influence(
        graph=graph,
        seeds=cfim_seeds,
        probability=p,
        num_simulations=num_sims,
        random_state=42,
    )
    cfim_by_comm = estimate_cascade_by_community(
        graph=graph,
        seeds=cfim_seeds,
        probability=p,
        num_simulations=num_sims // 2,
        random_state=42,
    )
    cfim_ugap = utility_gap(cfim_by_comm)

    pof_welfare_k = 1 - (welfare_total_influence_k / greedy_total_influence_k) if greedy_total_influence_k > 0 else 0
    pof_cfim_vs_greedy = 1 - (cfim_total_influence / greedy_total_influence_k) if greedy_total_influence_k > 0 else 0
    pof_cfim_vs_welfare = 1 - (cfim_total_influence / welfare_total_influence_k) if welfare_total_influence_k > 0 else 0

    return {
        'greedy_total_influence': greedy_total_influence_k,
        'greedy_ugap': greedy_ugap_k,
        'welfare_total_influence': welfare_total_influence_k,
        'welfare_ugap': welfare_ugap_k,
        'cfim_total_influence': cfim_total_influence,
        'cfim_ugap': cfim_ugap,
        'pof_welfare_vs_greedy': pof_welfare_k,
        'pof_cfim_vs_greedy': pof_cfim_vs_greedy,
        'pof_cfim_vs_welfare': pof_cfim_vs_welfare
    }


def average_results(results_list):
    """Average results across multiple runs"""
    if not results_list:
        return {}

    averaged = {}
    for key in results_list[0].keys():
        values = [r[key] for r in results_list]
        averaged[key + '_mean'] = statistics.mean(values)
        averaged[key + '_std'] = statistics.stdev(values) if len(values) > 1 else 0.0

    return averaged


print(f"Running baseline SBM experiments with {num_runs} runs each...")

# Test 1: Welfare variants with k = 1% of |V|
print("\n=== TEST 1: Welfare variants with 1% of |V| seeds ===")

# Get graph size from first run
graph, costs = create_sbm_graph(seed=42)
N = graph.number_of_nodes()
seed_frac = 0.01
k_fixed = max(1, math.ceil(seed_frac * N))
print(f"Using k = {k_fixed} seeds ({seed_frac * 100:.1f}% of |V| = {N})")

alphas = [0.9, 0.5, 0.1, 0.0, -3, -7, -9]
results_alpha = []

# First, collect greedy baselines for all runs
print("Computing greedy baselines for all runs...")
greedy_baselines = []
for run in range(num_runs):
    print(f"Computing greedy baseline for run {run + 1}/{num_runs}")
    graph, costs = create_sbm_graph(seed=42 + run)
    baseline = compute_greedy_baseline(graph, k_fixed)
    greedy_baselines.append(baseline)

# Now run each alpha using the precomputed baselines
for alpha in alphas:
    print(f"\n--- Running for alpha = {alpha} (k = {k_fixed}) ---")

    alpha_results = []
    for run in range(num_runs):
        print(f"Run {run + 1}/{num_runs} for alpha = {alpha}")
        graph, costs = create_sbm_graph(seed=42 + run)
        result = run_test1_single_alpha(graph, costs, k_fixed, alpha, greedy_baselines[run])
        alpha_results.append(result)

    alpha_averaged = average_results(alpha_results)

    print(f"Results for alpha = {alpha}:")
    print(
        f"  Welfare Influence: {alpha_averaged['welfare_total_influence_mean']:.4f} ± {alpha_averaged['welfare_total_influence_std']:.4f}")
    print(
        f"  Welfare Utility Gap: {alpha_averaged['welfare_ugap_mean']:.4f} ± {alpha_averaged['welfare_ugap_std']:.4f}")
    print(
        f"  C-FIM Influence: {alpha_averaged['cfim_total_influence_mean']:.4f} ± {alpha_averaged['cfim_total_influence_std']:.4f}")
    print(f"  C-FIM Utility Gap: {alpha_averaged['cfim_ugap_mean']:.4f} ± {alpha_averaged['cfim_ugap_std']:.4f}")

    results_alpha.append({
        "alpha": alpha,
        "k": k_fixed,
        "seed_fraction": seed_frac,
        "total_influence_greedy_mean": round(alpha_averaged['greedy_total_influence_mean'], 4),
        "total_influence_greedy_std": round(alpha_averaged['greedy_total_influence_std'], 4),
        "total_influence_welfare_mean": round(alpha_averaged['welfare_total_influence_mean'], 4),
        "total_influence_welfare_std": round(alpha_averaged['welfare_total_influence_std'], 4),
        "total_influence_cfim_mean": round(alpha_averaged['cfim_total_influence_mean'], 4),
        "total_influence_cfim_std": round(alpha_averaged['cfim_total_influence_std'], 4),
        "utility_gap_greedy_mean": round(alpha_averaged['greedy_ugap_mean'], 4),
        "utility_gap_greedy_std": round(alpha_averaged['greedy_ugap_std'], 4),
        "utility_gap_welfare_mean": round(alpha_averaged['welfare_ugap_mean'], 4),
        "utility_gap_welfare_std": round(alpha_averaged['welfare_ugap_std'], 4),
        "utility_gap_cfim_mean": round(alpha_averaged['cfim_ugap_mean'], 4),
        "utility_gap_cfim_std": round(alpha_averaged['cfim_ugap_std'], 4),
        "price_of_fairness_welfare_mean": round(alpha_averaged['pof_welfare_mean'], 4),
        "price_of_fairness_welfare_std": round(alpha_averaged['pof_welfare_std'], 4),
        "price_of_fairness_cfim_mean": round(alpha_averaged['pof_cfim_mean'], 4),
        "price_of_fairness_cfim_std": round(alpha_averaged['pof_cfim_std'], 4),
    })

print("\n=== TEST 2: C-FIM with different budgets (alpha = -3) vs Welfare Greedy ===")
alpha_fixed = -3
budget_fracs = [0.005, 0.01, 0.03, 0.05, 0.1]
results_budget = []

for budget_frac in budget_fracs:
    # Seed count k as a fraction of |V|
    k_budget = max(1, min(N, math.ceil(budget_frac * N)))
    print(f"\n--- Running for k = {k_budget} seeds ({budget_frac * 100:.1f}% of |V|) ---")

    budget_results = []
    for run in range(num_runs):
        print(f"Run {run + 1}/{num_runs} for k = {k_budget}")
        graph, costs = create_sbm_graph(seed=42 + run)
        result = run_test2_single(graph, costs, k_budget, alpha_fixed)
        budget_results.append(result)

    budget_averaged = average_results(budget_results)

    print(f"Results for k = {k_budget}:")
    print(
        f"  Welfare Influence: {budget_averaged['welfare_total_influence_mean']:.4f} ± {budget_averaged['welfare_total_influence_std']:.4f}")
    print(
        f"  C-FIM Influence: {budget_averaged['cfim_total_influence_mean']:.4f} ± {budget_averaged['cfim_total_influence_std']:.4f}")

    results_budget.append({
        "alpha": alpha_fixed,
        "k": k_budget,
        "budget_fraction": budget_frac,
        "total_influence_greedy_mean": round(budget_averaged['greedy_total_influence_mean'], 4),
        "total_influence_greedy_std": round(budget_averaged['greedy_total_influence_std'], 4),
        "total_influence_welfare_mean": round(budget_averaged['welfare_total_influence_mean'], 4),
        "total_influence_welfare_std": round(budget_averaged['welfare_total_influence_std'], 4),
        "total_influence_cfim_mean": round(budget_averaged['cfim_total_influence_mean'], 4),
        "total_influence_cfim_std": round(budget_averaged['cfim_total_influence_std'], 4),
        "utility_gap_greedy_mean": round(budget_averaged['greedy_ugap_mean'], 4),
        "utility_gap_greedy_std": round(budget_averaged['greedy_ugap_std'], 4),
        "utility_gap_welfare_mean": round(budget_averaged['welfare_ugap_mean'], 4),
        "utility_gap_welfare_std": round(budget_averaged['welfare_ugap_std'], 4),
        "utility_gap_cfim_mean": round(budget_averaged['cfim_ugap_mean'], 4),
        "utility_gap_cfim_std": round(budget_averaged['cfim_ugap_std'], 4),
        "price_of_fairness_welfare_vs_greedy_mean": round(budget_averaged['pof_welfare_vs_greedy_mean'], 4),
        "price_of_fairness_welfare_vs_greedy_std": round(budget_averaged['pof_welfare_vs_greedy_std'], 4),
        "price_of_fairness_cfim_vs_greedy_mean": round(budget_averaged['pof_cfim_vs_greedy_mean'], 4),
        "price_of_fairness_cfim_vs_greedy_std": round(budget_averaged['pof_cfim_vs_greedy_std'], 4),
        "price_of_fairness_cfim_vs_welfare_mean": round(budget_averaged['pof_cfim_vs_welfare_mean'], 4),
        "price_of_fairness_cfim_vs_welfare_std": round(budget_averaged['pof_cfim_vs_welfare_std'], 4),
    })

# Save results
output_csv_alpha = "welfare_comparison_alpha_results_averaged_sbm.csv"
with open(output_csv_alpha, mode="w", newline="") as file:
    fieldnames = [
        "alpha", "k", "seed_fraction",
        "total_influence_greedy_mean", "total_influence_greedy_std",
        "total_influence_welfare_mean", "total_influence_welfare_std",
        "total_influence_cfim_mean", "total_influence_cfim_std",
        "utility_gap_greedy_mean", "utility_gap_greedy_std",
        "utility_gap_welfare_mean", "utility_gap_welfare_std",
        "utility_gap_cfim_mean", "utility_gap_cfim_std",
        "price_of_fairness_welfare_mean", "price_of_fairness_welfare_std",
        "price_of_fairness_cfim_mean", "price_of_fairness_cfim_std",
    ]
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(results_alpha)

output_csv_budget = "welfare_comparison_budget_results_averaged_sbm.csv"
with open(output_csv_budget, mode="w", newline="") as file:
    fieldnames = [
        "alpha", "k", "budget_fraction",
        "total_influence_greedy_mean", "total_influence_greedy_std",
        "total_influence_welfare_mean", "total_influence_welfare_std",
        "total_influence_cfim_mean", "total_influence_cfim_std",
        "utility_gap_greedy_mean", "utility_gap_greedy_std",
        "utility_gap_welfare_mean", "utility_gap_welfare_std",
        "utility_gap_cfim_mean", "utility_gap_cfim_std",
        "price_of_fairness_welfare_vs_greedy_mean", "price_of_fairness_welfare_vs_greedy_std",
        "price_of_fairness_cfim_vs_greedy_mean", "price_of_fairness_cfim_vs_greedy_std",
        "price_of_fairness_cfim_vs_welfare_mean", "price_of_fairness_cfim_vs_welfare_std",
    ]
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(results_budget)

print(f"\nTest 1 averaged results saved to {output_csv_alpha}")
print(f"Test 2 averaged results saved to {output_csv_budget}")
print(f"Each result is averaged over {num_runs} independent runs")